namespace: sahil-ns 

replicas: 6

appDeployment:
 labels:
  app: ecommerce
 name: ecommerce-conatiner

image:
 repository: svsps/E-commerce
 tag: v1.0.0
port: 80

appService:
 app: ecommerce
 port: 80
 type: LoadBalancer


